### ISSUE TITLE
NameError: name 'sam3d' is not defined

### ISSUE THREAD

**Issue by wxy127** [DinhHieuHoang/SAM3D#5]
from sam3d.run.default_configuration import get_default_configuration
from sam3d.paths import default_plans_identifier
from sam3d.utilities.task_name_id_conversion import convert_id_to_task_name 
NameError: name 'sam3d' is not defined

**Comment by tanbuinhat** [comment]
Hi, sorry for late response!

The error is because you are not in the folder path. You should cd to the folder that has the code
