### ISSUE TITLE
About ABSTRACT

### ISSUE THREAD

**Issue by yyy1998-i** [DinhHieuHoang/SAM3D#6]
Hello author, thank you for your excellent work, I encountered a confusion when reading your article, and then in the summary you said, Unlike traditional slice-by-slice processing, SAM3D extracts features across the entire volume. Is it because traditional slicing only slices labeled layers? While SAM3D is slicing all layers, is this also the reason to remove the prompt encoder of the original sam? My understanding is that there is no point in giving hints for unlabeled layers

**Comment by hdhieu1811** [comment]
The SAM-based works before ours split the 3D image into a stack of 2D images then processing them separately. We also split 3D image into 2D ones but only for encoding, then training from scratch a new 3D decoder so we can utilize information from the depth dimension.

The reason why we remove the prompt encoder of the original SAM is that (1) the original dataset used in the training of SAM consists of natural images that the text encoder cannot understand medical terms, (2) our decoder is 3D-convolutional which is not suitable for blending information in token-style like the transformer decoder of the original SAM. More precisely, blending information from multiple modalities is not in our scope.

Hope this information is useful to you.

**Comment by yyy1998-i** [comment]
I see, thank you for your reply in a timely manner
